### PR TITLE
Improve media attachment & link integration

### PR DESCRIPTION
**Pull request by andrew-gardener**
Added optional Kaltura media upload feature. If enabled, audio/video files will automatically be uploaded to Kaltura seamlessly. Default settings have mp4, webm, mov files for video and mp3 files for audio with a 250 MB upload limit.

Modified how attachments are displayed to allow viewing more attachment file types inline. Also parse though assignment description/answer content for links (a tags) and allow viewing some of these inline. This includes links to some files types (pdf, images, html5 compatible videos, and html5 compatible audio), popular media outlets (youtube, vimeo, spotify, and sound cloud), and some social media sites (for now only twitter).

New UI elements listing attachments and external resources needs review

Related #470, #420

### CODE REVIEW

**Comment by lenglund** [comment]
Review how "external resources" and attachments appear. Upload videos to test Kaltura.

**Comment by lenglund** [comment]
I would suggest the following changes:

changes

Rationale:
* Taking the options to open up a link out of the context the link is presented in will likely lead to confusion, especially if multiple links are used and/or there is significant text after the link(s). Let's simplify to just the pop-up option next to the link.
* More clarity is needed to show that an attachment has two distinct options for access. I'd prefer a stacked approach, with a button for the pop-up option.
* Can we also show the number of attachments (even though I think this is always 1 with the current restriction) in the header?

**Comment by lenglund** [comment]
I also wonder if we can pass the answer # assigned in the comparison when someone opens up a pop-up window when comparing. That is, can we display as a heading in the pop-up window "Answer #1" etc?

**Comment by andrew-gardener** [comment]
@lenglund made requested modifications:
- added inline pupup button to embeddable links in content
- added attachment count (which will always be 1 until we decide to allow more) and displayed popup button and show below option as requested.
- Show "Answer #"+num when showing popups in comparison screen

**Pull request merged**
