### PR TITLE
Add comparison draft state to assignment status

### LINKED ISSUE #624: Add state and UI change for comparison draft
We want to enable and implement changing "Compare Pairs" buttons to "Finish Comparing" when a draft has been saved.

### PR DESCRIPTION
**Pull request by andrew-gardener**
Closes #624

### CODE REVIEW

**Comment by lenglund** [comment]
When I submit a round that is not the last round, I get a brief error message for "Bad Gateway" that seems related to the comparison feedback boxes. But then the comparison seems to submit properly. Just my local or...?

**Comment by lenglund** [comment]
Otherwise, looks good. I like the "Finish Comparison" vs. "Finish Comparing" since it matches with "Finish Answer" (not answering).

**Comment by andrew-gardener** [comment]
@lenglund can't reproduce the issue on my machine. We can wait until next week to see what's happening

**Comment by lenglund** [comment]
Issue is local dev. This PR is good to go.

**Pull request merged**
