### PR TITLE
Add LTI consumer management screen

### PR DESCRIPTION
**Pull request by andrew-gardener**
Completes #472
Depends on pull request #488

### CODE REVIEW

**Comment by lenglund** [comment]
Is this a UI, workflow, or both review?

**Comment by andrew-gardener** [comment]
@lenglund UI mainly but feel free to review workflow as well if you have time

**Comment by lenglund** [comment]
Whoops, made comments in #472. =)

**Comment by andrew-gardener** [comment]
@lenglund Addressed issues listed in #472

**Pull request merged**
