### PR TITLE
Add group management functions

### LINKED ISSUE #806: Add in group management
Once group functionality is implemented for assignment, we may want to provide better management of groups. Right now, groups cannot be edited or deleted, only added (and students added/removed from each).

Options to edit or delete the groups themselves could possibly be launched from the Manage Users screen or accessed from this screen with a "Manage Groups" button (which would launch a new Manage Groups screen). Requires further discussion before implementing.

### PR DESCRIPTION
**Pull request by kitsook**
Backend:
- Remove db unique constraint on (course id, group name). Group name can be
repeated as long as there is only one active record with that name. Use
program logic to check instead of db constraint. This may introduce a
race condition, but the chance is small and impact is minimal
- Add group_answer_exists attribute to group model and return it in API
- Change logic of group creation API to check duplication for active
records only

Frontend:
- Add UI to edit group name
- Add UI to delete group name if no answer submitted for the group

Closes #806

### CODE REVIEW

**Comment by lenglund** [comment]
Great to see progress on this, thank you!

Requests:
* For consistency, I’d like to be able to cancel the manage modal with text in the top-right corner, with the same result as cancelling the add new modal (popup disappears and keeps me at the same spot on the page)
* Instead of loading a modal on top of a modal, can clicking edit on a group name instead replace the manage modal with the edit modal, with an additional back button allowing the user to return to the manage view (see [screenshot in the original issue](https://github.com/ubc/compair/issues/806#issuecomment-436387329))
* Please update text for the Edit Group screen to: “Edit the group name below and it will be updated for all users assigned to it. Groups can be used to give group-based assignments (where students submit one answer per group but complete comparisons and self-evaluations individually) and filter completed student answers and comparisons into smaller subsets to help with grading.” (and keep bolding as in original Add Group screen)
* Can we also add access to the manage group names option in the dropdown for the bulk action (see screenshot below)?
bulk-manage

**Comment by kitsook** [comment]
@lenglund Thanks for reviewing this item. Changes made accordingly.  Some comments though:

- the "Cancel" link on the top right corner of the modal was removed because I found it a bit confusing.  After renaming / deleting groups, clicking on the "Cancel" link won't undo what have been changed.  It will just close the modal.  Anyway, I added the "Cancel" link back.  Please try it out and let me know if you want to keep it.

- Added the "Manage group names option" to the bulk action dropdown.  However, same as closing the "Add Group" modal, closing "Manage Groups" modal will refresh the page and thus loosing any student selection made. Maybe we should put it as a standalone button instead?

**Comment by lenglund** [comment]
Can you revisit my second request in the original comment to see if that is possible?

Also, is it possible to have cancelling the modal when no changes have been made NOT refresh the page?

**Comment by kitsook** [comment]
Revised.  Added the "back" button to the edit modal.  Also changed to logic to refresh the group list instead of the whole page when closing the manage groups modal.

**Comment by lenglund** [comment]
Thank you! Only nit is back button needs class "btn-default". I will run by the working group.

**Comment by kitsook** [comment]
Thx for reviewing it.  Added `btn-default` to the "back" button

**Comment by lenglund** [comment]
Thanks for your work on this! The working group had no further feedback

**Pull request merged**
