### PR TITLE
Fix student rank view

### LINKED ISSUE #593: Student rank not made visible
Issue with conditional display of parent div where rank was moved to in assignment-view-partial:
`<div class="manager-actions pull-right" ng-if="(canManageAssignment && !answerFilters.anonymous) || (answer.user_id == loggedInUserId && assignment.answer_period && !assignment.compare_period)">`

Conditions need to apply to edit and delete actions; not to display of rank.

### PR DESCRIPTION
**Pull request by andrew-gardener**
Closes #593

### CODE REVIEW

**Comment by lenglund** [comment]
Counts are off. This is using demo assignment data, but with "20 and up" selected for students to view:

local-rank

**Comment by lenglund** [comment]
#12 is skipped; 19 answers displayed when 20 should be shown.

**Comment by andrew-gardener** [comment]
Good catch, seems that ranking still takes deleted answers into account, fixing now

**Comment by andrew-gardener** [comment]
@xcompass Please have a look over the last commit since its back-end related

**Pull request merged**
