### PR TITLE
Add user management screens

### PR DESCRIPTION
**Pull request by andrew-gardener**
Admins can now view a list of all users in the system as well as manage the user's course settings in another screen.

Includes:
- Adjustments caching for group list
- A new sort order option to the user list endpoint
- A new user course endpoint only accessible to system admins

Completes: #191

### CODE REVIEW

**Comment by xcompass** [comment]
Do you need @lenglund to review this PR?

**Comment by andrew-gardener** [comment]
Add @lenglund as a reviewer

**Comment by lenglund** [comment]
Can we either hide the breadcrumb for "Users" OR not have it a clickable link for users who are not admins?

**Comment by lenglund** [comment]
The way the workflow is right now, profile and courses are at the same level for each user. So can the breadcrumb here be changed to "Home » Users » Manage <Name's> Courses"?

**Comment by lenglund** [comment]
Since there is no bulk selection option, the trailing "|" can be removed for both the main and course screens.

**Comment by lenglund** [comment]
Could no return for courses screen say "No courses found. Select <a>another user</a>?" (linking back to users screen)?

**Comment by lenglund** [comment]
Instead of start/end date, can we have a column on the course screen that instead indicates if that course is currently active? e.g., "Course Status" column with maybe three options: "Not yet started" / "Currently in progress", "Completed"?

**Comment by lenglund** [comment]
Looks great otherwise; I'm sure we (as the only admins) will revise more down the road, too...

**Comment by lenglund** [comment]
One more question: When a student is dropped, am I correct in remembering that we drop their answer from the answer screen (and from the answer pool), but the answer text is still available for display when it's been used in a comparison pair?

**Comment by andrew-gardener** [comment]
@lenglund to answer the question, yes (was fixed in #448)

Will get on the other items you listed. I remember having trouble getting the breadcrumbs to only display for certain user types but I'll look into it a bit deeper.

**Comment by andrew-gardener** [comment]
@lenglund addressed all the issues you listed 

Note that the only way to get the breadcrumbs working the way you wanted to was switch the route to be '/users' + '/users/:userId/course' for the users and user courses management screens

**Pull request merged**
